// Sector catalogue for research targeting. Sectors stay plain strings so custom text is always
// allowed; this list only powers suggestions. Labels are kept as the team uses them day to day.

export const SECTORS: readonly string[] = [
  // Sağlık & estetik
  'Dental Klinik',
  'Dental Clinic',
  'Estetik Klinik',
  'Aesthetic Clinic',
  'Saç Ekimi',
  'Plastik Cerrahi',
  'Dermatoloji',
  'Fertility / IVF Clinic',
  'Private Hospital',
  'Medical Tourism',
  'Dental Tourism',
  'Aesthetic Tourism',
  'Hair Transplant Tourism',
  'Medical Tourism Facilitator',
  'Clinic Group',
  'Hospital Group',
  'Diagnostic Center',
  'Laboratory',
  'Radiology Center',
  'Pharmacy Chain',
  'Dental Laboratory',
  'Medical Devices',
  'Medical Distribution',
  'Veterinary Clinic',
  'Wellness / Spa',
  'Healthtech',
  // Turizm & konaklama
  'Luxury Hotel',
  'Boutique Hotel',
  'Resort',
  'Hospitality Group',
  'Tourism / DMC',
  'Tour Operator',
  'Travel Agency',
  'Luxury Travel',
  'Corporate Travel',
  'MICE',
  'Destination Wedding',
  'VIP Transfer',
  'Chauffeur Service',
  'Yacht Charter',
  'Private Jet',
  'Cruise',
  'Boat Tour',
  'Excursion Company',
  'Adventure Tourism',
  'Villa Rental',
  'Holiday Rental',
  'Golf',
  'Golf Resort',
  'Ski Resort',
  'Beach Club',
  'Theme Park',
  'Attraction',
  'Luxury Concierge',
  'Traveltech',
  // Gayrimenkul & yapı
  'Property Management',
  'Real Estate Agency',
  'Luxury Real Estate',
  'Property Developer',
  'Real Estate Investment',
  'Commercial Real Estate',
  'Office Leasing',
  'Retail Leasing',
  'Property Consultancy',
  'Relocation Services',
  'Coworking',
  'Business Center',
  'Facility Management',
  'Interior Design',
  'Architecture',
  'Construction',
  'Construction Equipment',
  'Building Materials',
  'Stone / Marble',
  'Flooring',
  'Furniture',
  'Home Decoration',
  'Interior Products',
  'Kitchen & Bathroom',
  'Kitchen Manufacturer',
  'Bathroom Manufacturer',
  'Lighting',
  'Lighting Manufacturer',
  'Smart Home',
  'Home Automation',
  'HVAC',
  'Pool / Landscaping',
  'Home Services',
  'Cleaning Services',
  'Security Services',
  'Proptech',
  // Perakende, moda & güzellik
  'Luxury Retail',
  'Luxury Goods',
  'Luxury Brand',
  'Premium Brand',
  'Fashion',
  'Luxury Fashion',
  'Fashion Manufacturer',
  'Textile',
  'Jewelry',
  'Jewelry Manufacturer',
  'Watches',
  'Cosmetics',
  'Skincare',
  'Beauty Brand',
  'Beauty Distribution',
  'Perfume',
  'Haircare',
  'Beauty Salon',
  'Hair Salon',
  'Barber',
  'Art Gallery',
  'Auction House',
  'Antiques',
  'E-commerce',
  'Marketplace',
  'Marketplace Seller',
  'D2C Brand',
  'Consumer Brand',
  'Subscription Business',
  'Consumer Electronics',
  'Pet Services',
  // Otomotiv & mobilite
  'Automotive',
  'Luxury Automotive',
  'Car Rental',
  'Car Dealership',
  'Commercial Vehicles',
  'Fleet Services',
  'Mobility',
  'EV Charging',
  'Marine / Yacht Sales',
  'Marine Services',
  'Shipyard',
  'Yacht Refit',
  // Eğitim
  'Education',
  'Private School',
  'Language School',
  'University',
  'Online Education',
  'Edtech',
  'Training Company',
  'Corporate Education',
  'Sports Academy',
  // Profesyonel hizmetler & finans
  'Consulting',
  'Management Consultancy',
  'Business Consultancy',
  'Legal Services',
  'Corporate Law',
  'Immigration Law',
  'Immigration Consultancy',
  'Citizenship / Residency Consultancy',
  'Accounting',
  'Tax Advisory',
  'Finance',
  'Fintech',
  'Insurance',
  'Investment Company',
  'Investment Advisory',
  'Wealth Management',
  'Private Equity',
  'Venture Capital',
  'Mortgage Broker',
  'Recruitment',
  'Executive Search',
  'HR Services',
  'Professional Services',
  'B2B Services',
  // Teknoloji
  'B2B SaaS',
  'Software Company',
  'IT Services',
  'Cybersecurity',
  // Sanayi, ticaret & lojistik
  'Logistics',
  'Freight',
  'Shipping',
  'Import / Export',
  'Import Company',
  'Export Company',
  'Wholesale',
  'Manufacturing',
  'B2B Manufacturing',
  'Industrial Equipment',
  'Industrial Automation',
  'Machinery',
  'Equipment Rental',
  'Packaging',
  'Printing',
  'Solar Energy',
  'Renewable Energy',
  'Energy Services',
  // Yiyecek & içecek
  'Food & Beverage',
  'Food Manufacturing',
  'Beverage Brand',
  'Coffee Brand',
  'Restaurant',
  'Restaurant Group',
  'Fine Dining',
  'Cafe Chain',
  'Catering',
  'Franchise',
  'Restaurant Supply',
  'Hotel Supply',
  // Spor, etkinlik & medya
  'Fitness',
  'Gym',
  'Sports Club',
  'Events',
  'Event Venue',
  'Event Production',
  'Conference / Exhibition',
  'Wedding',
  'Wedding Venue',
  'Nightlife Venue',
  'Entertainment',
  'Photography / Production',
  'Creative Studio',
  'Media Company',
  'Marketing Agency',
];

/**
 * Broad sector families. Used only to pick plausible demo names today; Phase 4 can use them to
 * choose research strategies. Order matters: the first family whose keywords match wins.
 */
export type SectorFamily =
  | 'dental'
  | 'aesthetic'
  | 'medical'
  | 'hospitality'
  | 'transfer'
  | 'yacht'
  | 'villa'
  | 'travel'
  | 'realestate'
  | 'interior'
  | 'fashion'
  | 'beauty'
  | 'tech'
  | 'food'
  | 'general';

const FAMILY_KEYWORDS: [SectorFamily, string[]][] = [
  ['dental', ['dental', 'diş', 'dis klinig']],
  ['aesthetic', ['aesthetic', 'estetik', 'saç ekimi', 'hair transplant', 'plastik', 'dermatolo', 'skin', 'cosmetic center']],
  ['medical', ['clinic', 'klinik', 'hospital', 'hastane', 'medical', 'ivf', 'fertility', 'diagnostic', 'laboratory', 'radiology', 'pharmacy', 'health', 'wellness', 'spa', 'veterinary']],
  ['transfer', ['transfer', 'chauffeur', 'limousine', 'car rental', 'araç kiralama', 'fleet', 'mobility']],
  ['yacht', ['yacht', 'yat kiralama', 'marine', 'boat', 'shipyard', 'cruise']],
  ['villa', ['villa', 'holiday rental']],
  ['hospitality', ['hotel', 'otel', 'resort', 'hospitality', 'beach club', 'golf', 'ski']],
  ['travel', ['travel', 'tour', 'tur ', 'turizm', 'tourism', 'dmc', 'mice', 'excursion', 'seyahat', 'destination', 'concierge']],
  ['realestate', ['real estate', 'property', 'realty', 'leasing', 'mortgage', 'gayrimenkul', 'relocation', 'coworking', 'business center']],
  ['interior', ['interior', 'furniture', 'mobilya', 'decoration', 'kitchen', 'bathroom', 'lighting', 'architecture', 'flooring', 'marble', 'smart home', 'home automation', 'pool']],
  ['fashion', ['fashion', 'moda', 'jewel', 'watch', 'luxury retail', 'luxury goods', 'luxury brand', 'textile', 'boutique']],
  ['beauty', ['beauty', 'cosmetic', 'skincare', 'perfume', 'haircare', 'salon', 'barber']],
  ['tech', ['saas', 'software', 'it services', 'cyber', 'tech', 'fintech', 'digital']],
  ['food', ['restaurant', 'restoran', 'cafe', 'food', 'beverage', 'coffee', 'catering', 'dining']],
];

export function sectorFamily(sector: string): SectorFamily {
  const s = sector.toLocaleLowerCase('tr-TR');
  for (const [family, keywords] of FAMILY_KEYWORDS) {
    if (keywords.some((k) => s.includes(k))) return family;
  }
  return 'general';
}
