// CRM sector intelligence: what a CRM or lightweight operational system can realistically help a
// business of this type manage. This is GENERAL SECTOR GUIDANCE ("businesses like this commonly
// use a CRM for …"), never evidence about a specific company. Company facts come only from Phase 4
// research evidence; see domain/mail/context.ts for how the two stay separate.
//
// Inheritance: family profile + sector profile = the use cases for a prospect.
//   - Every family has a profile with use cases typical for that family.
//   - A sector profile `extends` its family: it adds sector-specific use cases (listed first) and
//     may `remove` inherited ones that do not apply (e.g. a vet clinic tracks pet history, not
//     "patient history").
//   - The generic profile is only a fallback for sectors KITE does not understand; it is never
//     merged into a family or sector profile.
import type { SectorFamilyId } from '../sectorTaxonomy/families';

export interface CrmUseCase {
  id: string;
  /** Short Turkish phrase for the UI and Turkish emails. */
  tr: string;
  /** Short English phrase for English emails. */
  en: string;
}

export interface CrmProfile {
  id: string;
  level: 'generic' | 'family' | 'sector';
  /** Parent profile (family profile id) for sector profiles. */
  extends?: string;
  /** One neutral sentence: how businesses of this type commonly use a CRM. Never a claim about a company. */
  summaryTr: string;
  summaryEn: string;
  useCases: CrmUseCase[];
  /** Inherited use case ids that do not apply to this sector. */
  removes?: string[];
}

const u = (id: string, tr: string, en: string): CrmUseCase => ({ id, tr, en });

/** Fallback for unknown sectors: plain business CRM only, no niche workflows. */
export const GENERIC_CRM_PROFILE: CrmProfile = {
  id: 'generic',
  level: 'generic',
  summaryTr: 'Bir CRM, gelen talepleri, müşteri kayıtlarını, satış aşamalarını ve takipleri tek yerde toplamak için kullanılabilir.',
  summaryEn: 'A CRM can bring incoming enquiries, customer records, sales stages and follow ups into one place.',
  useCases: [
    u('incoming_leads', 'gelen talepler ve müşteri adayları', 'incoming enquiries and leads'),
    u('contacts', 'kişi ve şirket kayıtları', 'contact and company records'),
    u('sales_stages', 'satış aşamaları', 'sales stages'),
    u('follow_ups', 'takip hatırlatmaları', 'follow up reminders'),
    u('tasks', 'ekip görevleri', 'team tasks'),
    u('documents', 'dokümanlar', 'documents'),
    u('payments', 'ödeme takibi', 'payment tracking'),
    u('customer_history', 'müşteri geçmişi', 'customer history'),
  ],
};

export const FAMILY_CRM_PROFILES: Record<SectorFamilyId, CrmProfile> = {
  health: {
    id: 'family:health',
    level: 'family',
    summaryTr: 'Sağlık işletmelerinde CRM; hasta taleplerini, randevuları, evrakları, ödemeleri ve takipleri tek yerde yönetmek için kullanılabilir.',
    summaryEn: 'Healthcare practices often use a CRM to manage patient enquiries, appointments, documents, payments and follow ups in one place.',
    useCases: [
      u('patient_enquiries', 'hasta talepleri ve hasta adayları', 'patient enquiries and new patient leads'),
      u('appointments', 'randevular', 'appointments'),
      u('patient_history', 'hasta geçmişi', 'patient history'),
      u('health_documents', 'evrak ve onam formları', 'documents and consent forms'),
      u('health_payments', 'ödemeler', 'payments'),
      u('health_follow_ups', 'tedavi sonrası takipler', 'post treatment follow ups'),
      u('staff_tasks', 'personel görevleri', 'staff tasks'),
    ],
  },
  tourism: {
    id: 'family:tourism',
    level: 'family',
    summaryTr: 'Turizm işletmelerinde CRM; rezervasyon taleplerini, misafir bilgilerini, ödemeleri ve operasyon görevlerini bir arada takip etmek için kullanılabilir.',
    summaryEn: 'Travel and hospitality businesses often use a CRM to keep booking requests, guest details, payments and operational tasks together.',
    useCases: [
      u('booking_requests', 'rezervasyon talepleri', 'booking requests'),
      u('booking_tracking', 'rezervasyon takibi', 'reservation tracking'),
      u('guest_details', 'misafir bilgileri', 'guest details'),
      u('balance_payments', 'ödeme ve kalan bakiye takibi', 'deposits and remaining balances'),
      u('special_requests', 'özel talepler', 'special requests'),
      u('ops_tasks', 'operasyon görevleri', 'operational tasks'),
      u('repeat_guests', 'tekrar gelen misafir geçmişi', 'returning guest history'),
    ],
  },
  real_estate: {
    id: 'family:real_estate',
    level: 'family',
    summaryTr: 'Gayrimenkul işletmelerinde CRM; müşteri taleplerini, portföy eşleştirmeyi, gösterimleri ve satış ya da kiralama sürecini takip etmek için kullanılabilir.',
    summaryEn: 'Real estate teams often use a CRM to track buyer and tenant enquiries, portfolio matching, viewings and the sales or rental pipeline.',
    useCases: [
      u('re_leads', 'yeni müşteri talepleri', 'new buyer and tenant enquiries'),
      u('portfolio_matching', 'portföy eşleştirme', 'matching listings to client needs'),
      u('client_preferences', 'müşteri tercihleri', 'client preferences'),
      u('viewings', 'gösterim (viewing) randevuları', 'viewing appointments'),
      u('agent_assignment', 'danışman ataması', 'agent assignment'),
      u('offers', 'teklif süreci', 'offers and negotiations'),
      u('contract_stages', 'sözleşme aşamaları', 'contract stages'),
      u('re_pipeline', 'satış ve kiralama süreci (pipeline)', 'sales and rental pipeline'),
      u('after_sale', 'satış sonrası takip', 'after sale follow up'),
    ],
  },
  retail: {
    id: 'family:retail',
    level: 'family',
    summaryTr: 'Perakende ve e ticaret işletmelerinde CRM; müşteri kayıtlarını, siparişleri, iade taleplerini ve tekrar satın almayı takip etmek için kullanılabilir.',
    summaryEn: 'Retail and e commerce businesses often use a CRM to keep customer records, orders, return requests and repeat purchases organised.',
    useCases: [
      u('customer_records', 'müşteri kayıtları ve satın alma geçmişi', 'customer records and purchase history'),
      u('order_tracking', 'sipariş takibi', 'order tracking'),
      u('returns', 'iade ve değişim talepleri', 'returns and exchange requests'),
      u('customer_questions', 'müşteri soruları', 'customer questions'),
      u('repeat_purchase', 'tekrar satın alma takibi', 'repeat purchase follow ups'),
      u('segments', 'müşteri segmentleri', 'customer segments'),
      u('b2b_requests', 'kurumsal ve toptan talepler', 'corporate and bulk enquiries'),
    ],
  },
  professional: {
    id: 'family:professional',
    level: 'family',
    summaryTr: 'Profesyonel hizmet işletmelerinde CRM; müşteri adaylarını, ilk görüşmeleri, teklifleri, dosya aşamalarını ve tahsilatı takip etmek için kullanılabilir.',
    summaryEn: 'Professional services firms often use a CRM to track prospective clients, first meetings, proposals, engagement stages and invoicing.',
    useCases: [
      u('client_leads', 'müşteri adayları', 'prospective clients'),
      u('first_meeting', 'ilk görüşmeler', 'first meetings'),
      u('proposals', 'teklifler', 'proposals'),
      u('engagement_stages', 'iş ve dosya aşamaları', 'engagement stages'),
      u('prof_documents', 'evrak takibi', 'document tracking'),
      u('prof_tasks', 'görevler ve süreler', 'tasks and deadlines'),
      u('billing', 'faturalama ve tahsilat', 'invoicing and collections'),
      u('client_history', 'müşteri geçmişi', 'client history'),
    ],
  },
  finance: {
    id: 'family:finance',
    level: 'family',
    summaryTr: 'Finans ve sigorta işletmelerinde CRM; başvuruları, evrak toplamayı, görüşmeleri ve yenileme tarihlerini takip etmek için kullanılabilir.',
    summaryEn: 'Finance and insurance businesses often use a CRM to track applications, document collection, client meetings and renewal dates.',
    useCases: [
      u('fin_leads', 'müşteri adayları', 'prospective clients'),
      u('applications', 'başvuru aşamaları', 'application stages'),
      u('fin_documents', 'evrak toplama', 'document collection'),
      u('compliance_docs', 'uyum (KYC) belgeleri', 'KYC and compliance documents'),
      u('client_meetings', 'müşteri görüşmeleri', 'client meetings'),
      u('renewals', 'yenileme tarihleri', 'renewal dates'),
      u('portfolio_history', 'müşteri portföy geçmişi', 'client portfolio history'),
    ],
  },
  education: {
    id: 'family:education',
    level: 'family',
    summaryTr: 'Eğitim kurumlarında CRM; öğrenci adaylarını, başvuruları, kayıtları, ödemeleri ve veli iletişimini takip etmek için kullanılabilir.',
    summaryEn: 'Education providers often use a CRM to track prospective students, applications, enrolments, payments and parent communication.',
    useCases: [
      u('student_leads', 'öğrenci adayları', 'prospective students'),
      u('applications_edu', 'başvurular', 'applications'),
      u('enrolment', 'kayıt', 'enrolment'),
      u('program_assignment', 'ders veya program ataması', 'class or programme assignment'),
      u('tuition', 'ödemeler', 'tuition payments'),
      u('parent_comms', 'veli iletişimi', 'parent communication'),
      u('attendance', 'devam durumu', 'attendance'),
      u('re_enrolment', 'kayıt yenileme', 're enrolment'),
    ],
  },
  beauty: {
    id: 'family:beauty',
    level: 'family',
    summaryTr: 'Güzellik ve bakım işletmelerinde CRM; müşteri adaylarını, randevuları, paketleri, seans haklarını ve tekrar ziyaretleri takip etmek için kullanılabilir.',
    summaryEn: 'Beauty and wellness businesses often use a CRM to track new client enquiries, appointments, packages, session credits and return visits.',
    useCases: [
      u('beauty_leads', 'müşteri adayları', 'new client enquiries'),
      u('consultations', 'konsültasyonlar', 'consultations'),
      u('beauty_appointments', 'randevular', 'appointments'),
      u('packages', 'paketler', 'packages'),
      u('session_credits', 'seans hakları', 'session credits'),
      u('beauty_payments', 'ödemeler', 'payments'),
      u('treatment_history', 'işlem geçmişi', 'treatment history'),
      u('return_visits', 'kontrol ve tekrar ziyaret', 'check ins and return visits'),
    ],
  },
  automotive: {
    id: 'family:automotive',
    level: 'family',
    summaryTr: 'Otomotiv işletmelerinde CRM; talepleri, randevuları, teklifleri, müşteri ve araç geçmişini ve satış sonrası takibi bir arada tutmak için kullanılabilir.',
    summaryEn: 'Automotive businesses often use a CRM to keep enquiries, appointments, quotes, customer and vehicle history and after sales follow ups together.',
    useCases: [
      u('auto_leads', 'müşteri talepleri', 'customer enquiries'),
      u('auto_appointments', 'randevular', 'appointments'),
      u('auto_quotes', 'teklifler', 'quotes'),
      u('vehicle_history', 'müşteri ve araç geçmişi', 'customer and vehicle history'),
      u('auto_payments', 'ödemeler', 'payments'),
      u('auto_after_sales', 'satış sonrası takip', 'after sales follow ups'),
    ],
  },
  construction: {
    id: 'family:construction',
    level: 'family',
    summaryTr: 'İnşaat ve yapı işletmelerinde CRM; müşteri adaylarını, teklifleri, proje aşamalarını, ödemeleri ve teslim süreçlerini takip etmek için kullanılabilir.',
    summaryEn: 'Construction businesses often use a CRM to track leads, quotes, project stages, payments and handovers.',
    useCases: [
      u('con_leads', 'müşteri adayları', 'leads'),
      u('con_quotes', 'teklifler', 'quotes'),
      u('project_stages', 'proje aşamaları', 'project stages'),
      u('con_payments', 'ödeme ve tahsilat', 'payments and collections'),
      u('con_documents', 'dokümanlar', 'documents'),
      u('subcontractors', 'taşeronlar', 'subcontractors'),
      u('con_tasks', 'görevler', 'tasks'),
      u('handover', 'teslim süreçleri', 'handovers'),
    ],
  },
  manufacturing: {
    id: 'family:manufacturing',
    level: 'family',
    summaryTr: 'Üretim işletmelerinde CRM; talepleri, fiyat tekliflerini, siparişleri, üretim aşamasını ve sevkiyatı takip etmek için kullanılabilir.',
    summaryEn: 'Manufacturers often use a CRM to track enquiries, price quotes, orders, production status and shipments.',
    useCases: [
      u('mfg_enquiries', 'talepler', 'enquiries'),
      u('price_quotes', 'fiyat teklifleri', 'price quotes'),
      u('mfg_orders', 'siparişler', 'orders'),
      u('production_stage', 'üretim aşaması', 'production status'),
      u('customer_approvals', 'müşteri onayları', 'customer approvals'),
      u('shipments', 'sevkiyat', 'shipments'),
      u('mfg_payments', 'ödemeler', 'payments'),
      u('mfg_after_sales', 'satış sonrası', 'after sales'),
    ],
  },
  logistics: {
    id: 'family:logistics',
    level: 'family',
    summaryTr: 'Lojistik işletmelerinde CRM; müşteri taleplerini, fiyat tekliflerini, sevkiyat ve teslimat aşamalarını ve istisnaları takip etmek için kullanılabilir.',
    summaryEn: 'Logistics companies often use a CRM to track customer requests, rate quotes, shipment and delivery stages and exceptions.',
    useCases: [
      u('log_requests', 'müşteri talepleri', 'customer requests'),
      u('rate_quotes', 'fiyat teklifleri', 'rate quotes'),
      u('log_shipments', 'sevkiyat', 'shipments'),
      u('delivery_stages', 'teslimat aşamaları', 'delivery stages'),
      u('log_documents', 'evraklar', 'shipping documents'),
      u('log_comms', 'müşteri iletişimi', 'customer communication'),
      u('log_payments', 'ödemeler', 'payments'),
      u('exceptions', 'sorun ve istisna yönetimi', 'issues and exceptions'),
    ],
  },
  food: {
    id: 'family:food',
    level: 'family',
    summaryTr: 'Yeme içme işletmelerinde CRM; rezervasyonları, grup ve etkinlik taleplerini, misafir tercihlerini ve kurumsal müşterileri takip etmek için kullanılabilir.',
    summaryEn: 'Food and beverage businesses often use a CRM to track reservations, group and event requests, guest preferences and corporate customers.',
    useCases: [
      u('reservations', 'rezervasyonlar', 'reservations'),
      u('group_events', 'grup ve etkinlik talepleri', 'group and event requests'),
      u('guest_preferences', 'misafir tercihleri', 'guest preferences'),
      u('corporate_customers', 'kurumsal müşteriler', 'corporate customers'),
      u('guest_feedback', 'misafir geri bildirimleri', 'guest feedback'),
      u('supplier_orders', 'tedarikçi siparişleri', 'supplier orders'),
    ],
  },
  sports: {
    id: 'family:sports',
    level: 'family',
    summaryTr: 'Spor ve fitness işletmelerinde CRM; üyelik adaylarını, üyelikleri, paketleri, ödemeleri ve yenilemeleri takip etmek için kullanılabilir.',
    summaryEn: 'Sports and fitness businesses often use a CRM to track membership enquiries, memberships, packages, payments and renewals.',
    useCases: [
      u('member_leads', 'üyelik adayları', 'membership enquiries'),
      u('memberships', 'üyelikler', 'memberships'),
      u('sport_packages', 'paketler', 'packages'),
      u('sport_payments', 'ödemeler', 'payments'),
      u('pt_sessions', 'PT seansları', 'personal training sessions'),
      u('membership_renewal', 'üyelik yenileme', 'membership renewals'),
      u('member_history', 'üye geçmişi', 'member history'),
      u('re_engagement', 'tekrar iletişim', 're engaging lapsed members'),
    ],
  },
  events: {
    id: 'family:events',
    level: 'family',
    summaryTr: 'Etkinlik işletmelerinde CRM; etkinlik taleplerini, teklifleri, tarih uygunluğunu, tedarikçileri ve ödemeleri takip etmek için kullanılabilir.',
    summaryEn: 'Event businesses often use a CRM to track event enquiries, proposals, date availability, suppliers and payments.',
    useCases: [
      u('event_enquiries', 'etkinlik talepleri', 'event enquiries'),
      u('event_proposals', 'teklifler', 'proposals'),
      u('date_availability', 'tarih ve mekan uygunluğu', 'date and venue availability'),
      u('supplier_coordination', 'tedarikçi koordinasyonu', 'supplier coordination'),
      u('event_payments', 'ödeme ve kapora', 'deposits and payments'),
      u('event_day_tasks', 'etkinlik günü görevleri', 'event day tasks'),
      u('client_approvals', 'müşteri onayları', 'client approvals'),
    ],
  },
  technology: {
    id: 'family:technology',
    level: 'family',
    summaryTr: 'Teknoloji şirketlerinde CRM; müşteri adaylarını, demo taleplerini, teklifleri, onboarding sürecini ve sözleşme yenilemelerini takip etmek için kullanılabilir.',
    summaryEn: 'Technology companies often use a CRM to track leads, demo requests, proposals, onboarding and contract renewals.',
    useCases: [
      u('tech_leads', 'müşteri adayları', 'leads'),
      u('demo_requests', 'demo talepleri', 'demo requests'),
      u('tech_proposals', 'teklif ve sözleşmeler', 'proposals and contracts'),
      u('onboarding', 'onboarding süreci', 'customer onboarding'),
      u('support_requests', 'destek talepleri', 'support requests'),
      u('contract_renewals', 'sözleşme yenilemeleri', 'contract renewals'),
      u('account_history', 'müşteri hesap geçmişi', 'account history'),
    ],
  },
  wholesale: {
    id: 'family:wholesale',
    level: 'family',
    summaryTr: 'Toptan satış ve distribütörlük işletmelerinde CRM; bayileri, satış temsilcilerini, teklifleri, siparişleri ve tahsilatları takip etmek için kullanılabilir.',
    summaryEn: 'Wholesalers and distributors often use a CRM to manage dealers, sales reps, quotes, orders and collections.',
    useCases: [
      u('dealers', 'bayi yönetimi', 'dealer management'),
      u('sales_reps', 'satış temsilcileri', 'sales rep activity'),
      u('ws_requests', 'müşteri talepleri', 'customer requests'),
      u('ws_quotes', 'teklifler', 'quotes'),
      u('ws_orders', 'siparişler', 'orders'),
      u('collections', 'tahsilatlar', 'collections'),
      u('product_requests', 'ürün talepleri', 'product requests'),
      u('reorders', 'tekrar siparişler', 'reorders'),
    ],
  },
  home_services: {
    id: 'family:home_services',
    level: 'family',
    summaryTr: 'Ev ve yerel hizmet işletmelerinde CRM; hizmet taleplerini, keşif randevularını, teklifleri, ekip planlamasını ve tekrarlayan işleri takip etmek için kullanılabilir.',
    summaryEn: 'Home and local service businesses often use a CRM to track service requests, site visits, quotes, team scheduling and recurring jobs.',
    useCases: [
      u('service_requests', 'hizmet talepleri', 'service requests'),
      u('site_visits', 'keşif randevuları', 'site visits'),
      u('hs_quotes', 'teklifler', 'quotes'),
      u('team_scheduling', 'ekip ve teknisyen planlama', 'team and technician scheduling'),
      u('work_orders', 'iş emirleri', 'work orders'),
      u('recurring_jobs', 'tekrarlayan bakım ve hizmetler', 'recurring jobs'),
      u('hs_payments', 'ödemeler', 'payments'),
      u('hs_history', 'müşteri geçmişi', 'customer history'),
    ],
  },
  media: {
    id: 'family:media',
    level: 'family',
    summaryTr: 'Medya ve yaratıcı hizmet işletmelerinde CRM; brief ve talepleri, teklifleri, proje aşamalarını, onayları ve faturalamayı takip etmek için kullanılabilir.',
    summaryEn: 'Media and creative businesses often use a CRM to track briefs, proposals, project stages, approvals and invoicing.',
    useCases: [
      u('briefs', 'brief ve talepler', 'briefs and enquiries'),
      u('media_proposals', 'teklifler', 'proposals'),
      u('media_projects', 'proje aşamaları', 'project stages'),
      u('revisions', 'revizyonlar ve onaylar', 'revisions and approvals'),
      u('deadlines', 'teslim tarihleri', 'delivery dates'),
      u('media_billing', 'faturalama', 'invoicing'),
      u('media_history', 'müşteri geçmişi', 'client history'),
    ],
  },
  energy: {
    id: 'family:energy',
    level: 'family',
    summaryTr: 'Enerji işletmelerinde CRM; proje taleplerini, keşifleri, teklifleri, kurulum aşamalarını ve bakım takibini yönetmek için kullanılabilir.',
    summaryEn: 'Energy businesses often use a CRM to manage project enquiries, site surveys, quotes, installation stages and maintenance follow ups.',
    useCases: [
      u('energy_leads', 'proje talepleri', 'project enquiries'),
      u('site_surveys', 'keşifler', 'site surveys'),
      u('energy_quotes', 'teklif ve fizibilite', 'quotes and feasibility'),
      u('installation', 'kurulum aşamaları', 'installation stages'),
      u('permits', 'izin ve evraklar', 'permits and paperwork'),
      u('energy_payments', 'ödemeler', 'payments'),
      u('maintenance', 'bakım takibi', 'maintenance follow ups'),
    ],
  },
};

const sector = (
  id: string,
  family: SectorFamilyId,
  summaryTr: string,
  summaryEn: string,
  useCases: CrmUseCase[],
  removes?: string[],
): CrmProfile => ({ id, level: 'sector', extends: FAMILY_CRM_PROFILES[family].id, summaryTr, summaryEn, useCases, ...(removes ? { removes } : {}) });

export const SECTOR_CRM_PROFILES: Record<string, CrmProfile> = Object.fromEntries(
  [
    // ---- Sağlık ----
    sector('dental_clinic', 'health',
      'Diş kliniklerinde CRM; hasta taleplerini, randevuları, tedavi planlarını, ödeme planlarını ve kontrol randevularını tek yerde yönetmek için kullanılabilir.',
      'Dental clinics often use a CRM to manage patient enquiries, appointments, treatment plans, payment plans and recall visits in one place.',
      [
        u('treatment_plans', 'tedavi planları', 'treatment plans'),
        u('treatment_stages', 'tedavi aşamaları', 'treatment stages'),
        u('payment_plans', 'ödeme planları', 'payment plans'),
        u('insurance_docs', 'sigorta ve evrak süreçleri', 'insurance paperwork'),
        u('recall', 'kontrol (recall) randevuları', 'recall appointments'),
        u('missed_appointments', 'kaçırılan randevu takibi', 'missed appointment follow ups'),
        u('branch_coordination', 'şube koordinasyonu', 'coordination between branches'),
      ]),
    sector('aesthetic_clinic', 'health',
      'Estetik kliniklerde CRM; konsültasyon taleplerini, randevuları, paketleri, seans haklarını ve işlem sonrası kontrolleri takip etmek için kullanılabilir.',
      'Aesthetic clinics often use a CRM to track consultation requests, appointments, packages, session credits and aftercare check ins.',
      [
        u('consultation_requests', 'konsültasyon talepleri', 'consultation requests'),
        u('aesthetic_packages', 'paketler ve seans hakları', 'packages and session credits'),
        u('before_after', 'öncesi ve sonrası kayıtları', 'before and after records'),
        u('aftercare', 'işlem sonrası kontroller', 'aftercare check ins'),
      ]),
    sector('hair_transplant', 'health',
      'Saç ekimi kliniklerinde CRM; uluslararası hasta taleplerini, fotoğraf değerlendirmesini, operasyon tarihini, transfer ve konaklamayı ve operasyon sonrası takibi yönetmek için kullanılabilir.',
      'Hair transplant clinics often use a CRM to manage international enquiries, photo assessments, surgery dates, travel arrangements and post op follow ups.',
      [
        u('photo_assessment', 'fotoğraf ile ön değerlendirme', 'photo based assessments'),
        u('surgery_scheduling', 'operasyon tarihi planlama', 'surgery date planning'),
        u('travel_coordination', 'transfer ve konaklama koordinasyonu', 'transfer and accommodation coordination'),
        u('post_op', 'operasyon sonrası takip', 'post op follow ups'),
      ]),
    sector('hospital', 'health',
      'Hastanelerde CRM; hasta taleplerini bölümlere yönlendirmek, check up paketlerini, kurumsal anlaşmaları ve uluslararası hastaları takip etmek için kullanılabilir.',
      'Hospitals often use a CRM to route patient enquiries to departments and track check up packages, corporate agreements and international patients.',
      [
        u('department_routing', 'bölümlere talep yönlendirme', 'routing enquiries to departments'),
        u('checkup_packages', 'check up paketleri', 'check up packages'),
        u('corporate_agreements', 'kurumsal anlaşmalar', 'corporate agreements'),
        u('international_patients', 'uluslararası hasta koordinasyonu', 'international patient coordination'),
      ]),
    sector('clinic_group', 'health',
      'Çok şubeli klinik gruplarında CRM; talepleri merkezi olarak toplayıp şubelere dağıtmak ve şubeler arası randevu ve takipleri koordine etmek için kullanılabilir.',
      'Multi location clinic groups often use a CRM to collect enquiries centrally, route them to branches and coordinate appointments and follow ups across locations.',
      [
        u('central_intake', 'merkezi talep toplama ve dağıtım', 'central enquiry intake and routing'),
        u('branch_coordination', 'şube koordinasyonu', 'coordination between branches'),
        u('branch_reporting', 'şube bazlı raporlama', 'per branch reporting'),
      ]),
    sector('medical_tourism', 'health',
      'Sağlık turizminde CRM; uluslararası hasta taleplerini, tedavi tekliflerini, seyahat ve konaklama planını ve tedavi sonrası uzaktan takibi yönetmek için kullanılabilir.',
      'Medical travel businesses often use a CRM to manage international enquiries, treatment quotes, travel and accommodation plans and remote aftercare.',
      [
        u('intl_enquiries', 'uluslararası hasta talepleri', 'international patient enquiries'),
        u('treatment_quotes', 'tedavi teklifleri', 'treatment quotes'),
        u('travel_coordination', 'transfer ve konaklama koordinasyonu', 'transfer and accommodation coordination'),
        u('interpreters', 'tercüman ataması', 'interpreter assignment'),
        u('remote_aftercare', 'tedavi sonrası uzaktan takip', 'remote aftercare'),
      ]),
    sector('diagnostics', 'health',
      'Tanı ve laboratuvar merkezlerinde CRM; tetkik randevularını, sonuç bildirimlerini, hekim yönlendirmelerini ve kurumsal anlaşmaları takip etmek için kullanılabilir.',
      'Diagnostic centres and labs often use a CRM to track test appointments, result notifications, physician referrals and corporate agreements.',
      [
        u('test_appointments', 'tetkik randevuları', 'test appointments'),
        u('result_notifications', 'sonuç bildirimleri', 'result notifications'),
        u('referrals', 'hekim ve kurum yönlendirmeleri', 'physician and partner referrals'),
        u('corporate_agreements', 'kurumsal anlaşmalar', 'corporate agreements'),
      ],
      ['health_follow_ups']),
    sector('veterinary', 'health',
      'Veteriner kliniklerinde CRM; evcil hayvan ve sahip bilgilerini, aşı geçmişini, tedavi takiplerini ve periyodik kontrolleri takip etmek için kullanılabilir.',
      'Veterinary clinics often use a CRM to keep pet and owner records, vaccination history, treatment follow ups and recurring check ups together.',
      [
        u('pet_owner', 'evcil hayvan ve sahip ilişkisi', 'pet and owner records'),
        u('vaccinations', 'aşı geçmişi ve hatırlatmaları', 'vaccination history and reminders'),
        u('vet_follow_ups', 'tedavi takipleri', 'treatment follow ups'),
        u('recurring_checks', 'periyodik kontroller', 'recurring check ups'),
      ],
      ['patient_history', 'health_follow_ups']),
    sector('therapy_practice', 'health',
      'Terapi ve fizik tedavi merkezlerinde CRM; danışan taleplerini, seans planlarını, paketleri ve ilerleme takibini yönetmek için kullanılabilir.',
      'Therapy and physiotherapy practices often use a CRM to manage client enquiries, session plans, packages and progress follow ups.',
      [
        u('session_plans', 'seans planları', 'session plans'),
        u('therapy_packages', 'paketler ve seans hakları', 'packages and session credits'),
        u('progress_tracking', 'ilerleme takibi', 'progress tracking'),
      ]),

    // ---- Turizm ----
    sector('hotel', 'tourism',
      'Otellerde CRM; rezervasyon ve satış taleplerini, ödemeleri, misafir taleplerini, housekeeping ve bakım görevlerini takip etmek için kullanılabilir.',
      'Hotels often use a CRM to track booking and sales enquiries, payments, guest requests and housekeeping and maintenance tasks.',
      [
        u('hotel_sales', 'satış ve rezervasyon talepleri', 'sales and booking enquiries'),
        u('housekeeping', 'housekeeping koordinasyonu', 'housekeeping coordination'),
        u('maintenance_requests', 'bakım talepleri', 'maintenance requests'),
        u('supplies', 'sarf malzeme ve stok takibi', 'supplies and stock tracking'),
        u('task_management', 'görev yönetimi', 'task management'),
        u('group_corporate', 'grup ve kurumsal rezervasyonlar', 'group and corporate bookings'),
      ]),
    sector('villa_rental', 'tourism',
      'Villa kiralama işletmelerinde CRM; müsaitliği, rezervasyonları, depozitoları, giriş çıkış operasyonunu, temizliği ve mülk sahibi raporlarını takip etmek için kullanılabilir.',
      'Villa rental businesses often use a CRM to track availability, bookings, deposits, check in and check out, cleaning and owner reporting.',
      [
        u('availability', 'müsaitlik takvimi', 'availability calendar'),
        u('deposits', 'depozito takibi', 'deposits'),
        u('checkin_checkout', 'giriş ve çıkış operasyonu', 'check in and check out'),
        u('cleaning_maintenance', 'temizlik ve bakım', 'cleaning and maintenance'),
        u('owner_reports', 'mülk sahibi raporları', 'owner reporting'),
      ]),
    sector('tour_travel', 'tourism',
      'Tur ve seyahat işletmelerinde CRM; rezervasyonları, misafir bilgilerini, rehber ve transfer planlamasını, ödemeleri ve tur durumunu takip etmek için kullanılabilir.',
      'Tour and travel companies often use a CRM to track bookings, guest details, guide and transfer planning, payments and tour status.',
      [
        u('guide_assignment', 'rehber atamaları', 'guide assignments'),
        u('transfers', 'transferler', 'transfers'),
        u('tour_status', 'tur durumu', 'tour status'),
        u('agency_partners', 'acente ve iş ortakları', 'agency partners'),
      ]),
    sector('transfer', 'tourism',
      'Transfer işletmelerinde CRM; transfer taleplerini, sürücü ve araç atamalarını, uçuş saatlerini, ödemeleri ve kurumsal hesapları takip etmek için kullanılabilir.',
      'Transfer and chauffeur companies often use a CRM to track ride requests, driver and vehicle assignments, flight times, payments and corporate accounts.',
      [
        u('ride_requests', 'transfer talepleri', 'transfer requests'),
        u('driver_assignment', 'sürücü ve araç ataması', 'driver and vehicle assignment'),
        u('flight_tracking', 'uçuş saatleri takibi', 'flight time tracking'),
        u('corporate_accounts', 'kurumsal hesaplar', 'corporate accounts'),
      ],
      ['booking_requests']),
    sector('charter', 'tourism',
      'Yat ve jet kiralama işletmelerinde CRM; müsaitliği, teklifleri, sözleşme ve depozitoyu, mürettebat ve operasyonu ve özel talepleri takip etmek için kullanılabilir.',
      'Charter companies often use a CRM to track availability, quotes, contracts and deposits, crew and operations and special requests.',
      [
        u('availability', 'müsaitlik takvimi', 'availability calendar'),
        u('charter_quotes', 'teklif ve sözleşme', 'quotes and contracts'),
        u('deposits', 'depozito takibi', 'deposits'),
        u('crew_ops', 'mürettebat ve operasyon', 'crew and operations'),
      ]),
    sector('hospitality_venue', 'tourism',
      'Beach club ve eğlence mekanlarında CRM; masa ve loca rezervasyonlarını, etkinlik gecelerini, ön ödemeleri ve VIP misafirleri takip etmek için kullanılabilir.',
      'Beach clubs and venues often use a CRM to track table bookings, event nights, prepayments and VIP guests.',
      [
        u('table_bookings', 'masa ve loca rezervasyonları', 'table and lounge bookings'),
        u('event_nights', 'etkinlik geceleri', 'event nights'),
        u('prepayments', 'ön ödemeler', 'prepayments'),
        u('vip_guests', 'VIP misafirler', 'VIP guests'),
      ],
      ['ops_tasks']),
    sector('attraction', 'tourism',
      'Turistik tesislerde CRM; grup ve okul rezervasyonlarını, kurumsal etkinlikleri, sezonluk biletleri ve acente anlaşmalarını takip etmek için kullanılabilir.',
      'Attractions often use a CRM to track group and school bookings, corporate events, season passes and agency agreements.',
      [
        u('group_bookings', 'grup ve okul rezervasyonları', 'group and school bookings'),
        u('corporate_events', 'kurumsal etkinlikler', 'corporate events'),
        u('season_passes', 'sezonluk bilet ve üyelikler', 'season passes'),
        u('agency_partners', 'acente ve iş ortakları', 'agency partners'),
      ]),

    // ---- Gayrimenkul ----
    sector('property_developer', 'real_estate',
      'Proje geliştiricilerde CRM; satış ofisi taleplerini, ön satış ve rezervasyonları, ödeme planlarını, broker ağını ve alıcı bilgilendirmesini takip etmek için kullanılabilir.',
      'Developers often use a CRM to track sales office enquiries, off plan reservations, payment plans, broker networks and buyer updates.',
      [
        u('presales', 'ön satış ve rezervasyonlar', 'off plan reservations'),
        u('developer_payment_plans', 'ödeme planları', 'payment plans'),
        u('broker_network', 'broker ağı', 'broker network'),
        u('buyer_updates', 'inşaat aşaması bilgilendirmeleri', 'construction progress updates for buyers'),
      ]),
    sector('property_management', 'real_estate',
      'Mülk yönetimi işletmelerinde CRM; kiracı ve bakım taleplerini, kira tahsilatını, sözleşme yenilemelerini ve mülk sahibi raporlarını takip etmek için kullanılabilir.',
      'Property managers often use a CRM to track tenant and maintenance requests, rent collection, lease renewals and owner reporting.',
      [
        u('tenant_requests', 'kiracı talepleri', 'tenant requests'),
        u('maintenance_requests', 'bakım ve arıza talepleri', 'maintenance requests'),
        u('rent_collection', 'kira tahsilatı', 'rent collection'),
        u('lease_renewals', 'sözleşme yenilemeleri', 'lease renewals'),
        u('owner_reports', 'mülk sahibi raporları', 'owner reporting'),
      ],
      ['portfolio_matching', 'offers']),
    sector('coworking', 'real_estate',
      'Ortak çalışma alanlarında CRM; tur taleplerini, üyelikleri, oda rezervasyonlarını, faturalamayı ve üye taleplerini takip etmek için kullanılabilir.',
      'Coworking operators often use a CRM to track tour requests, memberships, room bookings, invoicing and member requests.',
      [
        u('tour_requests', 'tur talepleri', 'tour requests'),
        u('cw_memberships', 'üyelikler', 'memberships'),
        u('room_bookings', 'toplantı odası rezervasyonları', 'meeting room bookings'),
        u('cw_billing', 'faturalama', 'invoicing'),
      ],
      ['portfolio_matching', 'agent_assignment']),

    // ---- İnşaat ----
    sector('design_project', 'construction',
      'Mimarlık ve iç mimarlık ofislerinde CRM; proje taleplerini, teklifleri, tasarım onaylarını, revizyonları ve uygulama ekibi koordinasyonunu takip etmek için kullanılabilir.',
      'Architecture and interior design studios often use a CRM to track project enquiries, proposals, design approvals, revisions and contractor coordination.',
      [
        u('design_approvals', 'tasarım onayları', 'design approvals'),
        u('design_revisions', 'revizyonlar', 'revisions'),
        u('contractor_coordination', 'uygulama ekibi ve tedarikçi koordinasyonu', 'contractor and supplier coordination'),
      ]),
    sector('equipment_rental', 'construction',
      'Ekipman kiralama işletmelerinde CRM; ekipman müsaitliğini, kiralama sözleşmelerini, depozitoyu, teslim ve iadeyi ve hasar ve bakım kayıtlarını takip etmek için kullanılabilir.',
      'Equipment rental companies often use a CRM to track availability, rental agreements, deposits, delivery and returns and damage and maintenance records.',
      [
        u('equipment_availability', 'ekipman müsaitliği', 'equipment availability'),
        u('rental_agreements', 'kiralama sözleşmeleri', 'rental agreements'),
        u('deposits', 'depozito takibi', 'deposits'),
        u('delivery_return', 'teslim ve iade', 'delivery and returns'),
        u('damage_maintenance', 'hasar ve bakım takibi', 'damage and maintenance records'),
      ],
      ['subcontractors', 'project_stages']),

    // ---- Perakende ----
    sector('ecommerce', 'retail',
      'E ticaret işletmelerinde CRM; sipariş ve kargo sorularını, iade taleplerini, müşteri segmentlerini ve tekrar satın almayı takip etmek için kullanılabilir.',
      'Online stores often use a CRM to handle order and delivery questions, returns, customer segments and repeat purchase follow ups.',
      [
        u('delivery_questions', 'sipariş ve kargo soruları', 'order and delivery questions'),
        u('post_purchase', 'satın alma sonrası iletişim', 'post purchase communication'),
      ]),
    sector('marketplace', 'retail',
      'Pazaryerlerinde CRM; satıcı başvurularını, satıcı onboarding sürecini, alıcı ve satıcı destek taleplerini takip etmek için kullanılabilir.',
      'Marketplaces often use a CRM to manage seller applications, seller onboarding and buyer and seller support requests.',
      [
        u('seller_applications', 'satıcı başvuruları', 'seller applications'),
        u('seller_onboarding', 'satıcı onboarding', 'seller onboarding'),
        u('marketplace_support', 'alıcı ve satıcı destek talepleri', 'buyer and seller support'),
      ],
      ['returns']),
    sector('subscription', 'retail',
      'Abonelik işletmelerinde CRM; abonelik yenilemelerini, ödeme sorunlarını, plan değişikliklerini ve ayrılma riski olan müşterileri takip etmek için kullanılabilir.',
      'Subscription businesses often use a CRM to track renewals, failed payments, plan changes and customers at risk of cancelling.',
      [
        u('subscription_renewals', 'abonelik yenilemeleri', 'subscription renewals'),
        u('failed_payments', 'ödeme sorunları', 'failed payments'),
        u('plan_changes', 'plan değişiklikleri', 'plan changes'),
        u('churn_risk', 'ayrılma riski olan müşteriler', 'customers at risk of cancelling'),
      ]),
    sector('furniture_showroom', 'retail',
      'Mobilya ve mutfak showroomlarında CRM; ölçü ve keşif randevularını, özel siparişleri, üretim süresini, teslimat ve montajı ve satış sonrası servisi takip etmek için kullanılabilir.',
      'Furniture and kitchen showrooms often use a CRM to track measuring visits, custom orders, lead times, delivery and installation and after sales service.',
      [
        u('measuring_visits', 'ölçü ve keşif randevuları', 'measuring visits'),
        u('custom_orders', 'özel siparişler', 'custom orders'),
        u('lead_times', 'üretim ve tedarik süreleri', 'production and lead times'),
        u('delivery_installation', 'teslimat ve montaj', 'delivery and installation'),
        u('after_sales_service', 'satış sonrası servis', 'after sales service'),
      ]),
    sector('collector_sales', 'retail',
      'Galeri, müzayede ve antika işletmelerinde CRM; koleksiyoner ilişkilerini, eser ilgisini, sergi davetlerini ve satış ve teslim süreçlerini takip etmek için kullanılabilir.',
      'Galleries and auction houses often use a CRM to track collector relationships, interest in specific works, exhibition invitations and sales and delivery.',
      [
        u('collectors', 'koleksiyoner ilişkileri', 'collector relationships'),
        u('artwork_interest', 'eser ilgisi takibi', 'interest in specific works'),
        u('exhibition_invites', 'sergi ve müzayede davetleri', 'exhibition and auction invitations'),
      ],
      ['returns', 'segments']),
    sector('franchise', 'retail',
      'Franchise sistemlerinde CRM; franchise başvurularını, aday değerlendirmesini, yeni şube onboarding sürecini ve şube destek taleplerini takip etmek için kullanılabilir.',
      'Franchise brands often use a CRM to track franchise applications, candidate evaluation, new unit onboarding and franchisee support requests.',
      [
        u('franchise_applications', 'franchise başvuruları', 'franchise applications'),
        u('candidate_evaluation', 'aday değerlendirme', 'candidate evaluation'),
        u('franchisee_onboarding', 'yeni şube onboarding', 'new franchisee onboarding'),
        u('franchisee_support', 'şube destek talepleri', 'franchisee support requests'),
      ]),

    // ---- Otomotiv ----
    sector('car_rental', 'automotive',
      'Araç kiralama işletmelerinde CRM; rezervasyonları, araç müsaitliğini, depozito ve ödemeyi, teslim ve iadeyi ve hasar ve bakım kayıtlarını takip etmek için kullanılabilir.',
      'Car rental companies often use a CRM to track reservations, fleet availability, deposits and payments, pick ups and returns and damage and maintenance records.',
      [
        u('rental_reservations', 'rezervasyonlar', 'reservations'),
        u('fleet_availability', 'araç müsaitliği', 'vehicle availability'),
        u('deposits', 'depozito', 'deposits'),
        u('pickup_return', 'teslim ve iade', 'pick ups and returns'),
        u('damage_maintenance', 'hasar ve bakım takibi', 'damage and maintenance records'),
        u('repeat_rentals', 'tekrar kiralama', 'repeat rentals'),
      ],
      ['auto_appointments', 'auto_quotes']),
    sector('car_dealership', 'automotive',
      'Otomobil bayilerinde CRM; satış taleplerini, test sürüşlerini, stok ve talep eşleştirmesini, finansman ve takası ve teslimat sonrası servisi takip etmek için kullanılabilir.',
      'Dealerships often use a CRM to track sales enquiries, test drives, stock matching, finance and trade ins and post delivery service.',
      [
        u('test_drives', 'test sürüşü randevuları', 'test drive appointments'),
        u('stock_matching', 'stok ve talep eşleştirme', 'matching stock to enquiries'),
        u('finance_tradein', 'finansman ve takas', 'finance and trade ins'),
        u('vehicle_delivery', 'araç teslimatı', 'vehicle handover'),
        u('service_reminders', 'servis hatırlatmaları', 'service reminders'),
      ]),
    sector('auto_service', 'automotive',
      'Servis işletmelerinde CRM; servis randevularını, araç geçmişini, iş emirlerini, parça ihtiyaçlarını, müşteri bilgilendirmesini ve bakım hatırlatmalarını takip etmek için kullanılabilir.',
      'Service workshops often use a CRM to track service bookings, vehicle history, job orders, parts, customer updates and maintenance reminders.',
      [
        u('service_bookings', 'servis randevuları', 'service bookings'),
        u('job_orders', 'iş emirleri', 'job orders'),
        u('parts', 'parça ihtiyaçları', 'parts requirements'),
        u('service_stages', 'servis aşamaları', 'service stages'),
        u('customer_updates', 'müşteri bilgilendirmesi', 'customer updates'),
        u('maintenance_reminders', 'sonraki bakım hatırlatması', 'next service reminders'),
      ],
      ['auto_appointments']),

    // ---- Eğitim ----
    sector('course_center', 'education',
      'Kurs ve dil okullarında CRM; deneme dersi taleplerini, seviye ve kur atamasını, ödemeleri, devamsızlığı ve kayıt yenilemeyi takip etmek için kullanılabilir.',
      'Course providers and language schools often use a CRM to track trial lesson requests, level placement, payments, attendance and re enrolment.',
      [
        u('trial_lessons', 'deneme dersi talepleri', 'trial lesson requests'),
        u('level_placement', 'seviye ve kur ataması', 'level placement'),
      ]),
    sector('corporate_training', 'education',
      'Kurumsal eğitim şirketlerinde CRM; kurumsal teklifleri, katılımcı listelerini, oturum planlamasını ve sertifikaları takip etmek için kullanılabilir.',
      'Corporate training companies often use a CRM to track proposals, participant lists, session scheduling and certificates.',
      [
        u('corporate_proposals', 'kurumsal teklifler', 'corporate proposals'),
        u('participants', 'katılımcı listeleri', 'participant lists'),
        u('session_scheduling', 'oturum planlama', 'session scheduling'),
        u('certificates', 'sertifikalar', 'certificates'),
      ],
      ['parent_comms', 're_enrolment']),

    // ---- Profesyonel hizmetler ----
    sector('law_firm', 'professional',
      'Hukuk bürolarında CRM; müvekkil adaylarını, ilk görüşmeleri, dosya ve dava aşamalarını, evrakları, görevleri ve tahsilatı takip etmek için kullanılabilir.',
      'Law firms often use a CRM to track prospective clients, initial consultations, matter stages, documents, tasks and billing.',
      [
        u('matter_stages', 'dosya ve dava süreçleri', 'matter and case stages'),
        u('legal_documents', 'evrak takibi', 'document tracking'),
        u('client_meetings_legal', 'görüşmeler', 'client meetings'),
        u('legal_deadlines', 'süre ve duruşma takvimi', 'deadlines and hearing dates'),
      ],
      ['engagement_stages', 'prof_documents']),
    sector('immigration', 'professional',
      'Göçmenlik ve oturum danışmanlığında CRM; ön değerlendirmeleri, evrak listelerini, başvuru aşamalarını ve resmi tarihleri takip etmek için kullanılabilir.',
      'Immigration and residency consultancies often use a CRM to track eligibility checks, document checklists, application stages and official deadlines.',
      [
        u('eligibility', 'uygunluk ön değerlendirmesi', 'eligibility assessments'),
        u('document_checklists', 'evrak listeleri', 'document checklists'),
        u('application_stages', 'başvuru aşamaları', 'application stages'),
        u('official_dates', 'resmi tarih takibi', 'official deadlines'),
      ]),
    sector('accounting', 'professional',
      'Muhasebe ve mali müşavirlik bürolarında CRM; müşteri evraklarını, beyanname takvimini, aylık işleri ve tahsilatı takip etmek için kullanılabilir.',
      'Accounting firms often use a CRM to track client documents, filing calendars, monthly work and collections.',
      [
        u('client_documents', 'müşteri evrak toplama', 'collecting client documents'),
        u('filing_calendar', 'beyanname takvimi', 'filing calendar'),
        u('monthly_work', 'aylık iş takibi', 'monthly work tracking'),
      ]),
    sector('recruitment', 'professional',
      'İşe alım şirketlerinde CRM; aday havuzunu, açık pozisyonları, mülakat aşamalarını ve işveren müşteri ilişkilerini takip etmek için kullanılabilir.',
      'Recruitment agencies often use a CRM to track candidate pools, open roles, interview stages and client relationships.',
      [
        u('candidate_pool', 'aday havuzu', 'candidate pool'),
        u('open_roles', 'açık pozisyonlar', 'open roles'),
        u('interview_stages', 'mülakat aşamaları', 'interview stages'),
        u('employer_clients', 'işveren müşteri ilişkileri', 'employer client relationships'),
      ]),

    // ---- Finans ----
    sector('insurance', 'finance',
      'Sigorta acentelerinde CRM; teklif taleplerini, poliçe yenilemelerini, hasar taleplerini ve müşteri görüşmelerini takip etmek için kullanılabilir.',
      'Insurance agencies often use a CRM to track quote requests, policy renewals, claims and client conversations.',
      [
        u('quote_requests', 'teklif talepleri', 'quote requests'),
        u('policy_renewals', 'poliçe yenilemeleri', 'policy renewals'),
        u('claims', 'hasar talepleri', 'claims'),
      ],
      ['portfolio_history']),
    sector('wealth', 'finance',
      'Varlık yönetimi ve yatırım danışmanlığında CRM; müşteri görüşmelerini, uygunluk belgelerini ve periyodik portföy değerlendirmelerini takip etmek için kullanılabilir.',
      'Wealth managers often use a CRM to track client reviews, compliance documents and periodic portfolio meetings.',
      [u('portfolio_reviews', 'periyodik portföy değerlendirmeleri', 'periodic portfolio reviews')],
      ['applications']),
    sector('deal_flow', 'finance',
      'Yatırım fonlarında CRM; yatırım fırsatlarını, değerlendirme aşamalarını, portföy şirketi ilişkilerini ve yatırımcı ilişkilerini takip etmek için kullanılabilir.',
      'Investment firms often use a CRM to track deal flow, evaluation stages, portfolio company relationships and investor relations.',
      [
        u('deal_pipeline', 'yatırım fırsatları (deal flow)', 'deal flow'),
        u('evaluation_stages', 'değerlendirme aşamaları', 'evaluation stages'),
        u('portfolio_companies', 'portföy şirketi ilişkileri', 'portfolio company relationships'),
        u('investor_relations', 'yatırımcı ilişkileri', 'investor relations'),
      ],
      ['applications', 'renewals']),

    // ---- Teknoloji ----
    sector('saas', 'technology',
      'Yazılım (SaaS) şirketlerinde CRM; demo ve deneme kullanıcılarını, onboarding sürecini, abonelik yenilemelerini ve ayrılma riskini takip etmek için kullanılabilir.',
      'SaaS companies often use a CRM to track demos and trials, onboarding, subscription renewals and churn risk.',
      [
        u('trials', 'deneme kullanıcıları', 'trial users'),
        u('subscription_renewals', 'abonelik yenilemeleri', 'subscription renewals'),
        u('churn_risk', 'ayrılma riski olan müşteriler', 'accounts at risk of churn'),
      ],
      ['contract_renewals']),

    // ---- Yeme içme ----
    sector('restaurant_group', 'food',
      'Çok şubeli restoran ve kafe gruplarında CRM; merkezi rezervasyonları, şube koordinasyonunu, kurumsal siparişleri ve misafir geri bildirimlerini takip etmek için kullanılabilir.',
      'Multi location restaurant groups often use a CRM to track central reservations, branch coordination, corporate orders and guest feedback.',
      [
        u('central_reservations', 'merkezi rezervasyon', 'central reservations'),
        u('branch_coordination', 'şube koordinasyonu', 'coordination between branches'),
        u('corporate_orders', 'kurumsal siparişler', 'corporate orders'),
      ]),
    sector('catering', 'food',
      'Catering işletmelerinde CRM; menü tekliflerini, etkinlik tarihi ve kişi sayısını, kapora ve ödemeleri ve tedarik planını takip etmek için kullanılabilir.',
      'Catering companies often use a CRM to track menu proposals, event dates and guest counts, deposits and payments and supply planning.',
      [
        u('menu_proposals', 'menü teklifleri', 'menu proposals'),
        u('event_details', 'etkinlik tarihi ve kişi sayısı', 'event dates and guest counts'),
        u('catering_payments', 'kapora ve ödemeler', 'deposits and payments'),
      ],
      ['reservations']),

    // ---- Spor ----
    sector('sports_academy', 'sports',
      'Spor akademilerinde CRM; öğrenci ve veli iletişimini, deneme antrenmanlarını, grup planlarını ve aidat takibini yönetmek için kullanılabilir.',
      'Sports academies often use a CRM to manage student and parent communication, trial sessions, group schedules and monthly fees.',
      [
        u('trial_sessions', 'deneme antrenmanları', 'trial sessions'),
        u('parent_comms', 'veli iletişimi', 'parent communication'),
        u('group_schedules', 'grup ve antrenman planı', 'group schedules'),
        u('monthly_fees', 'aidat takibi', 'monthly fees'),
      ],
      ['pt_sessions']),

    // ---- Etkinlik ----
    sector('event_venue', 'events',
      'Etkinlik ve düğün mekanlarında CRM; tarih uygunluğunu, mekan gezisi randevularını, teklif ve sözleşmeleri, kaporayı ve etkinlik detaylarını takip etmek için kullanılabilir.',
      'Event and wedding venues often use a CRM to track date availability, venue tours, proposals and contracts, deposits and event details.',
      [
        u('venue_tours', 'mekan gezisi randevuları', 'venue tours'),
        u('contracts', 'sözleşmeler', 'contracts'),
      ]),
    sector('exhibitions', 'events',
      'Kongre ve fuar organizatörlerinde CRM; katılımcı firmaları, stand satışını, sponsorlukları ve ziyaretçi kayıtlarını takip etmek için kullanılabilir.',
      'Exhibition and conference organisers often use a CRM to track exhibitors, stand sales, sponsorships and visitor registrations.',
      [
        u('exhibitors', 'katılımcı firmalar', 'exhibitors'),
        u('stand_sales', 'stand satışı', 'stand sales'),
        u('sponsorships', 'sponsorluklar', 'sponsorships'),
        u('visitor_registrations', 'ziyaretçi kayıtları', 'visitor registrations'),
      ]),
    sector('wedding', 'events',
      'Düğün organizasyonu işletmelerinde CRM; çiftlerle planlamayı, tedarikçi koordinasyonunu, bütçe ve ödemeleri ve düğün günü akışını takip etmek için kullanılabilir.',
      'Wedding planners often use a CRM to track planning with couples, supplier coordination, budgets and payments and the day of schedule.',
      [
        u('couple_planning', 'çiftlerle planlama', 'planning with couples'),
        u('budget', 'bütçe takibi', 'budget tracking'),
        u('day_schedule', 'düğün günü akışı', 'day of schedule'),
      ]),

    // ---- Medya ----
    sector('agency', 'media',
      'Ajans ve stüdyolarda CRM; yeni iş taleplerini, teklifleri, aylık hizmet alan müşterileri, onayları ve raporlama takvimini takip etmek için kullanılabilir.',
      'Agencies and studios often use a CRM to track new business enquiries, proposals, retainer clients, approvals and reporting schedules.',
      [
        u('retainers', 'aylık hizmet alan müşteriler', 'retainer clients'),
        u('reporting_calendar', 'raporlama takvimi', 'reporting schedule'),
      ]),

    // ---- Ev ve yerel hizmetler ----
    sector('pet_services', 'home_services',
      'Evcil hayvan hizmetlerinde CRM; evcil hayvan ve sahip bilgilerini, randevuları ve tekrarlayan bakım ziyaretlerini takip etmek için kullanılabilir.',
      'Pet service businesses often use a CRM to keep pet and owner details, appointments and recurring care visits together.',
      [
        u('pet_owner', 'evcil hayvan ve sahip ilişkisi', 'pet and owner records'),
        u('pet_appointments', 'randevular', 'appointments'),
      ],
      ['site_visits', 'work_orders']),
  ].map((p) => [p.id, p]),
);
