// The Phase 3 sector suggestion list, kept verbatim. These values may still be stored on research
// jobs and companies; every one of them resolves to a definition in catalog.ts (enforced by tests).
// Not shown in the UI.

export const LEGACY_SECTOR_VALUES: readonly string[] = [
  // Sağlık & estetik
  'Dental Klinik',
  'Dental Clinic',
  'Estetik Klinik',
  'Aesthetic Clinic',
  'Saç Ekimi',
  'Plastik Cerrahi',
  'Dermatoloji',
  'Fertility / IVF Clinic',
  'Private Hospital',
  'Medical Tourism',
  'Dental Tourism',
  'Aesthetic Tourism',
  'Hair Transplant Tourism',
  'Medical Tourism Facilitator',
  'Clinic Group',
  'Hospital Group',
  'Diagnostic Center',
  'Laboratory',
  'Radiology Center',
  'Pharmacy Chain',
  'Dental Laboratory',
  'Medical Devices',
  'Medical Distribution',
  'Veterinary Clinic',
  'Wellness / Spa',
  'Healthtech',
  // Turizm & konaklama
  'Luxury Hotel',
  'Boutique Hotel',
  'Resort',
  'Hospitality Group',
  'Tourism / DMC',
  'Tour Operator',
  'Travel Agency',
  'Luxury Travel',
  'Corporate Travel',
  'MICE',
  'Destination Wedding',
  'VIP Transfer',
  'Chauffeur Service',
  'Yacht Charter',
  'Private Jet',
  'Cruise',
  'Boat Tour',
  'Excursion Company',
  'Adventure Tourism',
  'Villa Rental',
  'Holiday Rental',
  'Golf',
  'Golf Resort',
  'Ski Resort',
  'Beach Club',
  'Theme Park',
  'Attraction',
  'Luxury Concierge',
  'Traveltech',
  // Gayrimenkul & yapı
  'Property Management',
  'Real Estate Agency',
  'Luxury Real Estate',
  'Property Developer',
  'Real Estate Investment',
  'Commercial Real Estate',
  'Office Leasing',
  'Retail Leasing',
  'Property Consultancy',
  'Relocation Services',
  'Coworking',
  'Business Center',
  'Facility Management',
  'Interior Design',
  'Architecture',
  'Construction',
  'Construction Equipment',
  'Building Materials',
  'Stone / Marble',
  'Flooring',
  'Furniture',
  'Home Decoration',
  'Interior Products',
  'Kitchen & Bathroom',
  'Kitchen Manufacturer',
  'Bathroom Manufacturer',
  'Lighting',
  'Lighting Manufacturer',
  'Smart Home',
  'Home Automation',
  'HVAC',
  'Pool / Landscaping',
  'Home Services',
  'Cleaning Services',
  'Security Services',
  'Proptech',
  // Perakende, moda & güzellik
  'Luxury Retail',
  'Luxury Goods',
  'Luxury Brand',
  'Premium Brand',
  'Fashion',
  'Luxury Fashion',
  'Fashion Manufacturer',
  'Textile',
  'Jewelry',
  'Jewelry Manufacturer',
  'Watches',
  'Cosmetics',
  'Skincare',
  'Beauty Brand',
  'Beauty Distribution',
  'Perfume',
  'Haircare',
  'Beauty Salon',
  'Hair Salon',
  'Barber',
  'Art Gallery',
  'Auction House',
  'Antiques',
  'E-commerce',
  'Marketplace',
  'Marketplace Seller',
  'D2C Brand',
  'Consumer Brand',
  'Subscription Business',
  'Consumer Electronics',
  'Pet Services',
  // Otomotiv & mobilite
  'Automotive',
  'Luxury Automotive',
  'Car Rental',
  'Car Dealership',
  'Commercial Vehicles',
  'Fleet Services',
  'Mobility',
  'EV Charging',
  'Marine / Yacht Sales',
  'Marine Services',
  'Shipyard',
  'Yacht Refit',
  // Eğitim
  'Education',
  'Private School',
  'Language School',
  'University',
  'Online Education',
  'Edtech',
  'Training Company',
  'Corporate Education',
  'Sports Academy',
  // Profesyonel hizmetler & finans
  'Consulting',
  'Management Consultancy',
  'Business Consultancy',
  'Legal Services',
  'Corporate Law',
  'Immigration Law',
  'Immigration Consultancy',
  'Citizenship / Residency Consultancy',
  'Accounting',
  'Tax Advisory',
  'Finance',
  'Fintech',
  'Insurance',
  'Investment Company',
  'Investment Advisory',
  'Wealth Management',
  'Private Equity',
  'Venture Capital',
  'Mortgage Broker',
  'Recruitment',
  'Executive Search',
  'HR Services',
  'Professional Services',
  'B2B Services',
  // Teknoloji
  'B2B SaaS',
  'Software Company',
  'IT Services',
  'Cybersecurity',
  // Sanayi, ticaret & lojistik
  'Logistics',
  'Freight',
  'Shipping',
  'Import / Export',
  'Import Company',
  'Export Company',
  'Wholesale',
  'Manufacturing',
  'B2B Manufacturing',
  'Industrial Equipment',
  'Industrial Automation',
  'Machinery',
  'Equipment Rental',
  'Packaging',
  'Printing',
  'Solar Energy',
  'Renewable Energy',
  'Energy Services',
  // Yiyecek & içecek
  'Food & Beverage',
  'Food Manufacturing',
  'Beverage Brand',
  'Coffee Brand',
  'Restaurant',
  'Restaurant Group',
  'Fine Dining',
  'Cafe Chain',
  'Catering',
  'Franchise',
  'Restaurant Supply',
  'Hotel Supply',
  // Spor, etkinlik & medya
  'Fitness',
  'Gym',
  'Sports Club',
  'Events',
  'Event Venue',
  'Event Production',
  'Conference / Exhibition',
  'Wedding',
  'Wedding Venue',
  'Nightlife Venue',
  'Entertainment',
  'Photography / Production',
  'Creative Studio',
  'Media Company',
  'Marketing Agency',
];
