// First contact mail drafts (Phase 5). Drafts are prepared and approved here; nothing is sent.
// Sending, the "İlk Temas" status change, replies and follow ups belong to later phases.
import type { ServiceKey } from '../services';
import type { EvidenceSourceType } from '../research';
import type { GuidanceSource } from '../sectorIntelligence';
import { countryMatchKey } from '../locations';

/**
 * review   = İncelenecek: produced or regenerated by the generator; Berk has not reviewed it yet.
 * draft    = Taslak: Berk saved his own edits; still being worked on.
 * approved = Onaylandı: approved for sending in a later phase. There is deliberately no "sent".
 */
export const MAIL_DRAFT_STATUSES = ['review', 'draft', 'approved'] as const;
export type MailDraftStatus = (typeof MAIL_DRAFT_STATUSES)[number];

export const MAIL_DRAFT_STATUS_LABELS: Record<MailDraftStatus, string> = {
  review: 'İncelenecek',
  draft: 'Taslak',
  approved: 'Onaylandı',
};

export type MailLanguage = 'tr' | 'en';

export const MAIL_LANGUAGE_LABELS: Record<MailLanguage, string> = {
  tr: 'Türkçe',
  en: 'İngilizce',
};

/** How much company-specific wording the evidence supports. Decided by code, not the model. */
export type Personalization = 'specific' | 'cautious' | 'general';

export const PERSONALIZATION_LABELS: Record<Personalization, string> = {
  specific: 'Şirkete özel',
  cautious: 'Temkinli',
  general: 'Genel',
};

/** Company evidence used by a draft: something KITE observed about this company (Phase 4). */
export interface MailEvidenceRef {
  kind: 'company_evidence';
  id: string;
  url: string;
  title: string;
  sourceType: EvidenceSourceType;
  claim: string;
  /** True only for pages KITE fetched and inspected itself. */
  inspected: boolean;
}

/** Sector guidance used by a draft: what businesses of this type commonly use the service for. */
export interface MailSectorContext {
  kind: 'sector_guidance';
  sectorLabel: string;
  sectorId: string | null;
  familyLabel: string | null;
  familyId: string | null;
  /** 'none' when the service has no sector intelligence yet (non-CRM services). */
  source: GuidanceSource | 'none';
  profileId: string | null;
  summaryTr: string | null;
  useCasesUsed: { id: string; tr: string }[];
  useCasesAvailable: { id: string; tr: string }[];
}

export interface MailGenerationNotes {
  provider: 'anthropic' | 'fixture';
  model: string | null;
  personalization: Personalization;
  /** Turkish, for Berk: why the draft is as specific (or as cautious) as it is. */
  personalizationReasons: string[];
  /** The one company-specific observation used, or null. Always backed by evidenceRefs. */
  companyObservation: string | null;
  serviceReasoning: string;
  /** Turkish notes, e.g. dash punctuation removed. */
  warnings: string[];
  promptVersion: string;
}

export interface MailDraftVersion {
  subject: string;
  body: string;
  savedAt: string;
  reason: 'before_regeneration';
}

export interface MailDraft {
  id: string;
  companyId: string;
  contactId: string | null;
  service: ServiceKey;
  language: MailLanguage;
  subjectOptions: string[];
  selectedSubject: string;
  body: string;
  status: MailDraftStatus;
  createdAt: string;
  updatedAt: string;
  generatedAt: string;
  approvedAt: string | null;
  researchJobId: string | null;
  evidenceRefs: MailEvidenceRef[];
  sectorContext: MailSectorContext;
  generationNotes: MailGenerationNotes;
  /** True when Berk changed the subject or body after the last generation. */
  editedSinceGeneration: boolean;
  /** Earlier versions kept when Berk regenerated over his own edits. Newest first. */
  previousVersions: MailDraftVersion[];
}

/** Türkiye prospects get Turkish, everyone else English. Berk can change it per draft. */
export function defaultMailLanguage(country: string): MailLanguage {
  return countryMatchKey(country) === 'TR' ? 'tr' : 'en';
}

/** Every draft is active in Phase 5 (nothing is sent), so a company has at most one. */
export function findActiveDraft(drafts: readonly MailDraft[], companyId: string): MailDraft | undefined {
  return drafts.find((d) => d.companyId === companyId);
}
